---
title: Making a Crowd Display with micro:bits and Python
hero_image: images/banner.png
description: Program a set of micro:bits so that they talk to each other via radio
  to create a synchonised light show
theme: red
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-1, manufacture-0, community-0
interests: ''
technologies: python, microbit
site_areas: jam
hardware: microbit
software: python
version: 4
last_tested: 2017-01-01
steps:
- title: Introduction
- title: What you will need
  completion: engaged
- title: Design your image
- title: Set up the radio
  completion: internal
- title: Triggering an avalanche of messages
